global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'api-guardian-monitor'

scrape_configs:
  - job_name: 'api-guardian'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.43.1:8080']
        labels:
          application: 'api-guardian'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']